apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-cert-controller
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - "apiextensions.k8s.io"
    resources:
    - "customresourcedefinitions"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
  - apiGroups:
    - "admissionregistration.k8s.io"
    resources:
    - "validatingwebhookconfigurations"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "endpoints"
    verbs:
    - "list"
    - "get"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "events"
    verbs:
    - "create"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - "leases"
    verbs:
    - "get"
    - "create"
    - "update"
    - "patch"
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "secretstores"
    - "clustersecretstores"
    - "externalsecrets"
    - "clusterexternalsecrets"
    - "pushsecrets"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "externalsecrets"
    - "externalsecrets/status"
    - "externalsecrets/finalizers"
    - "secretstores"
    - "secretstores/status"
    - "secretstores/finalizers"
    - "clustersecretstores"
    - "clustersecretstores/status"
    - "clustersecretstores/finalizers"
    - "clusterexternalsecrets"
    - "clusterexternalsecrets/status"
    - "clusterexternalsecrets/finalizers"
    - "pushsecrets"
    - "pushsecrets/status"
    - "pushsecrets/finalizers"
    verbs:
    - "update"
    - "patch"
  - apiGroups:
    - "generators.external-secrets.io"
    resources:
    - "acraccesstokens"
    - "ecrauthorizationtokens"
    - "fakes"
    - "gcraccesstokens"
    - "passwords"
    - "vaultdynamicsecrets"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "serviceaccounts"
    - "namespaces"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "get"
    - "list"
    - "watch"
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "delete"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "serviceaccounts/token"
    verbs:
    - "create"
  - apiGroups:
    - ""
    resources:
    - "events"
    verbs:
    - "create"
    - "patch"
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "externalsecrets"
    verbs:
    - "create"
    - "update"
    - "delete"
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-view
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "external-secrets.io"
    resources:
      - "externalsecrets"
      - "secretstores"
      - "clustersecretstores"
      - "pushsecrets"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
    - "generators.external-secrets.io"
    resources:
    - "acraccesstokens"
    - "ecrauthorizationtokens"
    - "fakes"
    - "gcraccesstokens"
    - "passwords"
    - "vaultdynamicsecrets"
    verbs:
      - "get"
      - "watch"
      - "list"
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-edit
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups:
      - "external-secrets.io"
    resources:
      - "externalsecrets"
      - "secretstores"
      - "clustersecretstores"
      - "pushsecrets"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
  - apiGroups:
    - "generators.external-secrets.io"
    resources:
    - "acraccesstokens"
    - "ecrauthorizationtokens"
    - "fakes"
    - "gcraccesstokens"
    - "passwords"
    - "vaultdynamicsecrets"
    verbs:
      - "create"
      - "delete"
      - "deletecollection"
      - "patch"
      - "update"
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-external-secrets-servicebindings
  labels:
    servicebinding.io/controller: "true"
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - "external-secrets.io"
    resources:
    - "externalsecrets"
    verbs:
    - "get"
    - "list"
    - "watch"
---
# Source: external-secrets-operator/charts/external-secrets/templates/cert-controller-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-external-secrets-cert-controller
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-external-secrets-cert-controller
subjects:
  - name: external-secrets-cert-controller
    namespace: "openshift-gitops"
    kind: ServiceAccount
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-external-secrets-controller
subjects:
  - name: release-name-external-secrets
    namespace: "openshift-gitops"
    kind: ServiceAccount
---
# Source: external-secrets-operator/templates/golang-external-secrets-hub-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: external-secrets-operator
  namespace: external-secrets-operator
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-external-secrets-leaderelection
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    resourceNames:
    - "external-secrets-controller"
    verbs:
    - "get"
    - "update"
    - "patch"
  - apiGroups:
    - ""
    resources:
    - "configmaps"
    verbs:
    - "create"
  - apiGroups:
    - "coordination.k8s.io"
    resources:
    - "leases"
    verbs:
    - "get"
    - "create"
    - "update"
    - "patch"
---
# Source: external-secrets-operator/charts/external-secrets/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-external-secrets-leaderelection
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-external-secrets-leaderelection
subjects:
  - kind: ServiceAccount
    name: release-name-external-secrets
    namespace: "openshift-gitops"
