# Source: external-secrets-operator/charts/external-secrets/templates/cert-controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-cert-controller
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-cert-controller
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-0.9.8
        app.kubernetes.io/name: external-secrets-cert-controller
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "v0.9.8"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: external-secrets-cert-controller
      automountServiceAccountToken: true
      hostNetwork: false
      containers:
        - name: cert-controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "ghcr.io/external-secrets/external-secrets:v0.9.8-ubi"
          imagePullPolicy: IfNotPresent
          args:
          - certcontroller
          - --crd-requeue-interval=5m
          - --service-name=release-name-external-secrets-webhook
          - --service-namespace=openshift-gitops
          - --secret-name=release-name-external-secrets-webhook
          - --secret-namespace=openshift-gitops
          - --metrics-addr=:8080
          - --healthz-addr=:8081
          
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
          readinessProbe:
            httpGet:
              port: 8081
              path: /readyz
            initialDelaySeconds: 20
            periodSeconds: 5
---
# Source: external-secrets-operator/charts/external-secrets/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-external-secrets
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-0.9.8
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "v0.9.8"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: release-name-external-secrets
      automountServiceAccountToken: true
      hostNetwork: false
      containers:
        - name: external-secrets
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "ghcr.io/external-secrets/external-secrets:v0.9.8-ubi"
          imagePullPolicy: IfNotPresent
          args:
          - --concurrent=1
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
---
# Source: external-secrets-operator/charts/external-secrets/templates/webhook-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-external-secrets-webhook
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-0.9.8
        app.kubernetes.io/name: external-secrets-webhook
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "v0.9.8"
        app.kubernetes.io/managed-by: Helm
    spec:
      hostNetwork: false
      serviceAccountName: external-secrets-webhook
      automountServiceAccountToken: true
      containers:
        - name: webhook
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          image: "ghcr.io/external-secrets/external-secrets:v0.9.8-ubi"
          imagePullPolicy: IfNotPresent
          args:
          - webhook
          - --port=10250
          - --dns-name=release-name-external-secrets-webhook.openshift-gitops.svc
          - --cert-dir=/tmp/certs
          - --check-interval=5m
          - --metrics-addr=:8080
          - --healthz-addr=:8081
          ports:
            - containerPort: 8080
              protocol: TCP
              name: metrics
            - containerPort: 10250
              protocol: TCP
              name: webhook
          readinessProbe:
            httpGet:
              port: 8081
              path: /readyz
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: certs
              mountPath: /tmp/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: release-name-external-secrets-webhook

