apiVersion: v1
kind: Secret
metadata:
  name: release-name-external-secrets-webhook
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-operator
  namespace: external-secrets-operator
  annotations:
    kubernetes.io/service-account.name: external-secrets-operator
type: kubernetes.io/service-account-token