apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-cert-controller
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-external-secrets
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-webhook
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
