# Source: external-secrets-operator/charts/external-secrets/templates/webhook-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-external-secrets-webhook
  namespace: "openshift-gitops"
  labels:
    helm.sh/chart: external-secrets-0.9.8
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v0.9.8"
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 10250
    protocol: TCP
    name: webhook
  selector:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: release-name
---
