apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: hub
          role: hub-role
          secretRef:
            key: token
            name: external-secrets-operator
            namespace: external-secrets-operator
      caProvider:
        key: tls.crt
        name: vault-secret-internal
        namespace: vault
        type: Secret
      path: secret
      server: "https://vault.vault.svc.cluster.local:8200"
      version: v2