apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-demo-secret
  namespace: config-demo
spec:
  dataFrom:
  - extract:
      key: secret/data/global/config-demo 
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore  
    name: vault-backend 
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: config-demo-secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque