# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: "dynamic-secret-output"
#   namespace: posgtresql
# spec:
#   refreshInterval: "768h"
#   target:
#     name: dynamic-secret-res
#   dataFrom:
#   - sourceRef:
#       generatorRef:
#         apiVersion: generators.external-secrets.io/v1alpha1
#         kind: VaultDynamicSecret
#         name: "dynamic-secret"
#         namespace: external-secrets-operator