apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgresql-vault-auth-sa
  namespace: postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-vault-auth-sa
  namespace: postgresql
  annotations:
    kubernetes.io/service-account.name: postgresql-vault-auth-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: postgresql-vault-auth-sa
  namespace: postgresql