# apiVersion: generators.external-secrets.io/v1alpha1
# kind: VaultDynamicSecret
# metadata:
#   name: "dynamic-secret"
#   namespace: postgresql
# spec:
#   path: "/database/creds/postgresql-role"
#   method: "GET"
#   provider:
#     server: "https://vault.vault.svc.cluster.local:8200"
#     version: v2
#     auth:
#         kubernetes:
#           mountPath: hub
#           role: hub-role
#           secretRef:
#             key: token
#             name: postgresql-vault-auth-sa 
#             namespace: postgresql
#     caProvider:
#         key: vault-secret-internal
#         name: vault-secret-internal
#         namespace: postgresql
#         type: Secret