apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops
  namespace: ngc-hub
  labels:
    validatedpatterns.io/pattern: ngc
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: in-cluster
    namespace: aap
  project: hub
  source:
    repoURL: https://github.com/rh-fran6/vanilla-gitops-deploy.git
    targetRevision: main
    path: infra/openshift-gitops-operator/overlays/default
  syncPolicy:
    automated: {}
    retry:
      limit: 20