apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: ngc-hub
  labels:
    validatedpatterns.io/pattern: ngc
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: in-cluster
    namespace: external-secrets-operator
  project: hub
  source:
    repoURL: https://github.com/rh-fran6/vanilla-gitops-deploy.git
    targetRevision: main
    path: infra/external-secrets-operator/operator/overlays/stable
  syncPolicy:
    automated: {}
    retry:
      limit: 20