apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: ngc-hub
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    name: in-cluster
    namespace: hello-world
  project: hello-world
  source:
    repoURL: https://github.com/rh-fran6/vanilla-gitops-deploy.git
    targetRevision: main
    path: charts/all/hello-world
  syncPolicy:
    automated: {}
    retry:
      limit: 20
