
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hub
  namespace: openshift-gitops
spec:
  description: App Project
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
status: {}
