apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: controller
  namespace: ansible-automation-platform
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  create_preload_data: true
  route_tls_termination_mechanism: Edge
  garbage_collect_secrets: true
  ingress_type: Route
  image_pull_policy: IfNotPresent
  task_privileged: false
  projects_persistence: false
  replicas: 3
  admin_user: admin
  auto_upgrade: true
  loadbalancer_ip: ""
  loadbalancer_port: 80
  loadbalancer_protocol: http
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  set_self_labels: true
