apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - ../../base
  - console.link.yaml

components:
  - ../../components/application-controller-cluster-admin
  - ../../components/edge-termination
  - ../../components/enable-notifications
  - ../../components/gitops-admins
  - ../../components/health-check-olm

patches:
  - target:
      kind: Subscription
      name: openshift-gitops-operator
    path: patch-channel.yaml
